MySQL database:
  user: root
  password: ''
  database: kitpvp
  port: 3306
  hostname: 127.0.0.1

# What is your permission for main staff commands etc.
PERMISSION.STAFF: ""

# Message for /staffantiabuse command?
ANTI.ABUSE.COMMAND:
  - ""
  - ""
  - ""
  - ""

# What is your creative command permission?
CREATIVE.PERMISSION: ""

# Players not allowed to join? Use this.
PLAYERS.NOT.ALLOWED:
  - ""
  - ""
  - ""
  - ""

# Command executed when a player not allowed to join, trys to join. Do not put a /.
COMMAND.EXECUTED.PLAYERS: ""


